blueprint:
  source_url: "https://raw.githubusercontent.com/tefracky/homeassistant-blueprints/blueprints/scripts/notification-delete.yaml"
  name: Lösche Benachrichtigung (Android & Persistent)
  description: >
    Dieses Skript löscht die persistente Benachrichtigung in Home Assistant
    und sendet auf den ausgewählten Android-Geräten einen "clear_notification"
    Befehl, um die Benachrichtigung auch dort zu entfernen.
  domain: script
  input:
    notify_device:
      name: Geräte für das Löschen der Benachrichtigung
      description: Wähle die Geräte aus, bei denen die Benachrichtigung gelöscht werden soll.
      selector:
        device:
          integration: mobile_app
          multiple: true
    notify_channel:
      name: Benachrichtigungskanal – Android & Persistent
      description: Der Kanalname, wie er bei der Benachrichtigung verwendet wurde.
      default: default-channel
      selector:
        text: {}
variables:
  notify_device: !input notify_device
  notify_channel: !input notify_channel

  filtered_devices: "{{ notify_device }}"

sequence:
  - service: persistent_notification.dismiss
    data:
      notification_id: "{{ notify_channel }}"
  - repeat:
      for_each: "{{ filtered_devices }}"
      sequence:
        - service: >
            notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}
          data:
            message: "clear_notification"
            data:
              tag: "{{ notify_channel }}"
